# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a85849636105efbfd86cffddf93fff4e425dbb4b91bc5222598307484d6efa54647b8cb0561a4770e44dd4560c393fb857fd913332bc2f8c5bda7b611f5c5ce

test:
  secret_key_base: 0060e6ccb250da8cb8d9e2ee92ea4c7be7432b21e585771a1569676efa6d481c06c8c22461093051251d3ecc262a7f974eb6f4a940c48aee2bb76f9d5edb80ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
